global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: '<host_ip>'
  smtp_from: '<sending@fromaddress>'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false


# The directory from which notification templates are read.
templates: 
- '/etc/alertmanager/template/*.tmpl'

# The root route on which each incoming alert enters.
route:
  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 1h

  # A default receiver
  receiver: <receiver_name1>

receivers:
- name: '<receiver_name1>'
  email_configs:
  - to: '<destionation_email>'
